nodejs/changelog-maker

README.md
changelog-maker.js

When working with a private repo, I was getting an error from onFetch() in commitTags():
> Error fetching issue #174: Error from GitHub: Not Found
Tracked this down to the scopes in authOptions being set to an empty array, which is fine for public repos.  
Added a `--private` argument that when set will set scopes to `['repo']` to allow ghissues to find the data it needs.

add --private arg to set repo scope, update readme - fixes Not Found error

---

commit-to-output.js

Fixes: https://github.com/rvagg/changelog-maker/issues/43
/R=@silverwind

escape <> in markdown

---

commit-to-output.js

added markdown escapes for _*~\

---

.github/workflows/test.yml
README.md

1. this requires #61 for the lock file addition. If you guys don't want a lockfile, I can change this to just use `npm i`
2. I don't know what exactly is required for tests to run. A token?
3. ~I also plan to add Windows testing later~ -- DONE, but I might need to drop it from here and tackle it later separately

Add GitHub Actions CI support.

---

.github/workflows/test.yml
.gitignore
collect-commit-labels.js
package-lock.json
package.json

Also:
* switch to `^` for all deps
* add missing properties in package.json
* add lock file

Update all dependencies

---

changelog-maker.js
collect-commit-labels.js

throws get in the way of promisified libraries so we can't use them for lazy cmdline error handling.

custom fatal() instead of throw

---

changelog-maker.js
commit-to-output.js
group-commits.js
test.js

Refs https://github.com/nodejs/node-core-utils/pull/388.
When auto-generating the commits for the commit message itself, we want them formatted in plaintext as specified in the [releasing guide](https://github.com/nodejs/node/blob/master/doc/guides/releases.md#5-create-release-commit). This adds a new format type to `changelog-maker` - `plaintext`.
Items formatted with this new type will take the following form:
```
doc:
* update napi_async_init documentation (Michael Dawson) https://github.com/nodejs/node/pull/33181
* doc and test URLSearchParams discrepancy (James M Snell) https://github.com/nodejs/node/pull/33236
* explicitly doc package.exports is breaking (Myles Borins) https://github.com/nodejs/node/pull/33074
* fix style and grammer in buffer.md (Nikolai Vavilov) …
```

feat: add commit-plaintext changelog formatting

---

collect-commit-labels.js
package-lock.json
package.json

With GitHub deprecating their old auth workflow ghauth@5 includes new options, for changelog-maker we're just going to go with the "make your own personal access token" since it's a per-user thing. I don't think there's a way to set one up with the oauth flow without having an app setup for it which I don't think makes sense.
Now when you run it you'll get:
```
Personal access token auth for Github.                                                                                                                
Enter a 40 character personal access token generated at                                                                                               
https://github.com/settings/tokens with the following scopes: repo …
```

update ghauth@5 with new github auth flow

---

commit-to-output.js
test.js

Alternate to https://github.com/nodejs/changelog-maker/pull/94
Only supports code span delimited with a single backtick char and gives up if it finds an edge case.
List of unsupported markdown-compliant edge cases I could think of:
```markdown
test: string ``code `span` with backticks inside`` not supported
test: string `code span ending with a backslash\\` not supported
test: string containing escaped \` `code span` not supported
`test`: message starting with a backslash not supported
```
I wasn't sure how to add tests for that, but it works from what I have tested locally.

feat: improve support of backtick strings

---

commit-to-output.js
test.js

Reverts nodejs/changelog-maker#122

Revert "feat: escape markdown characters in user provided strings"

---

.github/workflows/test-and-release.yml
README.md
changelog-maker.js
collect-commit-labels.js
commit-to-output.js
format.js
group-commits.js
groups.js
package.json
process-commits.js
reverts.js
test.js

* upgrade all deps, including ESM-only deps
* --simple is now default output, including colourising, with --markdown being an opt-in output format (that doesn't colourise).
* move process + print logic to separate module for exporting for simplifying branch-diff
* add --sha and --reverse options from branch-diff to dedupe some processing code (will open an PR over there that pulls this in)
The biggest change is that second item, the default output is nice for the terminal but if you want it for changelogs then you'll need to `--md` to get it and you won't have colourisation for that. The new markdown formatter and ansi don't mix. So this change will require some @nodejs/releasers input.
Change set is probably a bit for a full review, but if you're interested then maybe clone it and `npm …

feat!: switch to ESM, fix output colourising, dedupe more code w/ branch-diff

---

package.json

Enables https://github.com/nodejs/branch-diff/pull/50

feat: add collect-commit-labels to exports

---

README.md
auth.js
collect-commit-labels.js
find-matching-prs.js
package.json
process-commits.js
test.js

So .. I want to use `changelog-maker` for a project that doesn't use `PR-URL` metadata, and also, it really is kind of annoying to have to put that in when GitHub knows what commit belongs to what PR and we now have a useful way to query for it.
This introduces `--find-matching-prs=true` as an argument, then uses a GraphQL query to make a best guess as to what PR the commit belongs to and fills in the blanks for it. Because this is done before label collection it should also mean that we get to collect labels for commits that don't have `PR-URL` too, which is neat.
(If someone wants to go back and fix up #73 now that this introduces a GraphQL pattern so we can use it to find labels, then that might be neat too).

feat: --find-matching-prs for commits without PR-URL

---

CHANGELOG.md

Some version entries where at ### level instead of ##
problem found with [changelog-lint](https://github.com/chavacava/changelog-lint)

fix versions with bad nesting level

---

.github/workflows/test-and-release.yml
package.json

See also https://github.com/nodejs/branch-diff/pull/54

fix: update releaser action

---

test.js

Ref: https://github.com/nodejs/commit-stream/pull/10
The above change to commit-stream makes it strip out `(#xx)` from the summary and use it as one of the inputs to find the PR url. The change here just updates the test assertion to remove that from the commit—we don't need it and this is an improvement in functionality.

fix: make test pass

---

.github/workflows/test-and-release.yml

In preparation for #157 which will be a breaking change, forcing the dropping of 16.x.

chore: drop 16.x and add 20.x to CI

---

.github/workflows/test-and-release.yml
commit-to-output.js
package.json
test.js

This PR changes the commit output to include CVE-ID in the output (part of automation of security releases -  fixes: https://github.com/nodejs-private/security-release/issues/38)
Output:
```
➜  node (v18.20.4) ../changelog-maker/changelog-maker.js --group --markdown --filter-release --start-ref v18.20.3 --end-ref v18.20.4                                                                                                                        ✱
* \[[`85abedf1ff`](https://github.com/nodejs/node/commit/85abedf1ff)] - **(CVE-2024-22020)** **lib,esm**: handle bypass network-import via data: (RafaelGSS) [nodejs-private/node-private#522](https://github.com/nodejs-private/node-private/pull/522)
* \[[`eccd63b865`](https://github.com/nodejs/node/commit/eccd63b865)] - **(CVE-2024-36138)** **src**: …
```

feat: add CVE-ID to commit-output

---

groups.js
test.js

Support capturing `foo(bar)` as a commit's "group" in `foo(bar): message`, not just `foo` in `foo: message` which has been the standard Node.js style. I now almost exclusively use this on repos that use CC style and only just noticed they don't get bolded when there's a `(subthing)` in it.

Support conventional-commits style group matching

---

commit-to-output.js
test.js

Fixes: https://github.com/nodejs-private/security-release/issues/49

fix: add whitespace after cveId

---

changelog-maker.js
commit-to-list.js

Split commitToList to its own file will allow libraries to create their own custom format
Part of https://github.com/nodejs-private/security-release/issues/48 work

feat: split commit-to-list to its own file
